services:
  - type: web
    name: ecossistema-rh
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: rh-inovador-2026
      - key: WS_MAX_CONNECTIONS
        value: "5"
